version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0 # Java 17 Docker image

    working_directory: ~/MovingExpress/backend

    steps:
      - checkout

      - restore_cache:
          -keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}

      - run:
          name: Build and test Spring Boot application
          command: |
            ./gradlew clean build

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test

workflows:
  version: 2
  build:
    jobs:
      - build:
        config-path: backend/.circleci/config.yml  # Specify the path to your CircleCI configuration file

