version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0 # Java 17 Docker image
    working_directory: ~/MovingExpress
    steps:
        - checkout
        - run: echo "Running the build"
          name: build spring boot application
          command: ./gradlew clean build

workflows:
  version: 2
  build:
    jobs:
      - build