version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17-jdk # Java 17 Docker image

    working_directory: ~/MovingExpress/backend

    steps:
      - checkout

      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}

      - run:
          name: Build and test Spring Boot application
          command: |
            ./gradlew clean build

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}

workflows:
  version: 2
  build:
    jobs:
      - build
