version: 2.1

orbs:
  java: circleci/openjdk@0.13.0

jobs:
  build:
    docker:
      - image: cimg/base:2021.10
    steps:
      - checkout
      - java/install-jdk:
          jdk-version: 11

workflows:
  version: 2
  build:
    jobs:
      - build:
          config-path: backend/.circleci/config.yml  # Specify the path to your CircleCI configuration file
