version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0 # Java 17 Docker image
    working_directory: ~/MovingExpress
    steps:
        - checkout
        - run: 
            name: build spring boot application
            command: |
              cd backend
              ./gradlew clean build

jobs:
  build:
    docker:
      - image: cimg/node:16.13.1-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run:
          name: Run Tests
          command: cd ~/frontend/Tests && node .
