@startuml

!define TABLE(name) class name << (T,#FFAAAA) >>
!define PRIMARY_KEY(field) field << PK >>
!define FOREIGN_KEY(field) field << FK >>

skinparam class {
    BackgroundColor #f7f4eb
    BorderColor Black
}

skinparam classAttribute {
    BackgroundColor #f7f4eb
    BorderColor Black
}

Database "MySQL" as BoundedContextMySQL #f29111 {

        TABLE(Client) {
            PRIMARY_KEY(id) INT AUTO_INCREMENT
            clientId VARCHAR(36) UNIQUE NOT NULL
            firstName VARCHAR(255)
            lastName VARCHAR(255)
            email VARCHAR(255)
            phoneNumber VARCHAR(15)
        }

        TABLE(Truck) {
            PRIMARY_KEY(id) INT AUTO_INCREMENT
            vin VARCHAR(17) UNIQUE NOT NULL
            capacity DOUBLE
        }

        TABLE(Inventory) {
            PRIMARY_KEY(id) INT AUTO_INCREMENT
            inventoryId VARCHAR(36) UNIQUE NOT NULL
            description VARCHAR(255)
            FOREIGN_KEY(shipmentId) VARCHAR(36)
        }

        TABLE(Item) {
            PRIMARY_KEY(id) INT AUTO_INCREMENT
            itemId VARCHAR(36) UNIQUE NOT NULL
            itemName VARCHAR(255) NOT NULL
            type ENUM('ITEM', 'BOX') NOT NULL
            price DECIMAL(10, 2)
            description VARCHAR(255)
            weight DOUBLE
            handlingInstructions VARCHAR(255)
            FOREIGN_KEY(inventoryId) VARCHAR(36)
        }

        TABLE(Quote){
            PRIMARY_KEY(id) INT AUTO_INCREMENT
            quoteId VARCHAR(36) UNIQUE NOT NULL
            pickUpAddress VARCHAR(255)
            pickupCity VARCHAR(255)
            pickupPostalCode VARCHAR(10)
            dropOffAddress VARCHAR(255)
            dropoffCity VARCHAR(255)
            dropoffPostalCode VARCHAR(10)
            buildingTypePickUp VARCHAR(255)
            numberOfRoomsPickUp INT
            hasElevatorPickUp BOOLEAN
            buildingTypeDropOff VARCHAR(255)
            numberOfRoomsDropOff INT
            hasElevatorDropOff BOOLEAN
            clientEmail VARCHAR(255)
            movingEstimatorId VARCHAR(36)
            FOREIGN_KEY(clientEmail) VARCHAR(255)
            FOREIGN_KEY(movingEstimatorId) VARCHAR(36)
            FOREIGN_KEY(shipmentId) VARCHAR(36)
        }

        TABLE(Shipment) {
            PRIMARY_KEY(id) INT AUTO_INCREMENT
            shipmentId VARCHAR(36) UNIQUE NOT NULL
            shipmentStatus VARCHAR(255)
            shipmentDepartureAddress VARCHAR(255)
            shipmentArrivalAddress VARCHAR(255)
            FOREIGN_KEY(vin) VARCHAR(17)
            FOREIGN_KEY(clientId) VARCHAR(36)
        }

        TABLE(MovingCrew) {
            PRIMARY_KEY(id) INT AUTO_INCREMENT
            movingCrewId VARCHAR(36) UNIQUE NOT NULL
            type VARCHAR(255)
            FOREIGN_KEY(shipmentId) VARCHAR(36)
        }

        TABLE(Driver) {
            PRIMARY_KEY(id) INT AUTO_INCREMENT
            driverId VARCHAR(36) UNIQUE NOT NULL
            firstName VARCHAR(255)
            lastName VARCHAR(255)
            phoneNumber VARCHAR(15)
            email VARCHAR(255)
            FOREIGN_KEY(shipmentId) VARCHAR(36)
        }

        TABLE(ShipmentReviewer) {
            PRIMARY_KEY(id) INT AUTO_INCREMENT
            shipmentReviewerId VARCHAR(36)
            firstName VARCHAR(255)
            lastName VARCHAR(255)
            email VARCHAR(255)
            phoneNumber VARCHAR(15)
        }

        TABLE(Observer) {
            PRIMARY_KEY(id) INT AUTO_INCREMENT
            observerId VARCHAR(36) UNIQUE NOT NULL
            firstName VARCHAR(255)
            lastName VARCHAR(255)
            email VARCHAR(255)
            FOREIGN_KEY(shipmentId) VARCHAR(36)
        }

        TABLE(MovingEstimator) {
            PRIMARY_KEY(id) INT AUTO_INCREMENT
            estimatorId VARCHAR(36) UNIQUE NOT NULL
            firstName VARCHAR(255)
            lastName VARCHAR(255)
            email VARCHAR(255)
            phoneNumber VARCHAR(15)
            FOREIGN_KEY(shipmentId) VARCHAR(36)
        }

        TABLE(Report) {
            PRIMARY_KEY(id) INT AUTO_INCREMENT
            reportId VARCHAR(36) UNIQUE NOT NULL
            name VARCHAR(50)
            type VARCHAR(50)
            date DATETIME
            validity DATETIME
        }
}

    Client ||--|{ Shipment
    Truck }|--|| Shipment
    Shipment ||--|{ MovingCrew
    MovingCrew ||--o| Report
    Driver }|--|| Shipment
    Shipment ||--o{ Observer
    Shipment ||--|{ ShipmentReviewer
    Driver ||--|| Truck
    Inventory ||--o{ Item
    Client ||--o| Report
    Shipment ||--|{ Inventory
    Client ||--|{ Quote
    Quote ||--|{ Shipment
    MovingEstimator ||--|{ Quote
    MovingEstimator ||--o| Report

@enduml
