@startuml

!define TABLE(name) class name << (T,#FFAAAA) >>
!define PRIMARY_KEY(field) field << PK >>
!define FOREIGN_KEY(field) field << FK >>

skinparam class {
    BackgroundColor #f7f4eb
    BorderColor Black
}

skinparam classAttribute {
    BackgroundColor #f7f4eb
    BorderColor Black
}

rectangle "MySQL" as BoundedContextMySQL #line.dashed {

        TABLE(Customer) {
            PRIMARY_KEY(customerId) INT AUTO_INCREMENT
            firstName VARCHAR(255)
            lastName VARCHAR(255)
            email VARCHAR(255)
            phoneNumber VARCHAR(15)
        }

        TABLE(Truck) {
            PRIMARY_KEY(VIN) VARCHAR(255)
            capacity INT
        }

        TABLE(Inventory) {
            PRIMARY_KEY(inventoryId) INT AUTO_INCREMENT
            description VARCHAR(255)
        }

        TABLE(Item) {
            PRIMARY_KEY(itemId) INT AUTO_INCREMENT
            price DECIMAL(10, 2)
            picture BLOB
            handlingInstructions VARCHAR(255)
            FOREIGN_KEY(inventoryId) INT
        }

        TABLE(Box) {
            PRIMARY_KEY(boxId) INT AUTO_INCREMENT
            picture BLOB
            description VARCHAR(50)
            handlingInstructions VARCHAR(255)
            FOREIGN_KEY(inventoryId) INT
        }

        TABLE(Quote){
            PRIMARY_KEY(quoteId) INT AUTO_INCREMENT
            FOREIGN_KEY(customerId) INT
            pickUpLocation VARCHAR(50)
            dropOffDestination VARCHAR(50)
        }

        TABLE(Shipment) {
            PRIMARY_KEY(shipmentId) INT AUTO_INCREMENT
            shipmentStatus VARCHAR(255)
            shipmentDepartureAddress VARCHAR(255)
            shipmentArrivalAddress VARCHAR(255)
            FOREIGN_KEY(truckIdentifier) VARCHAR(255)
            FOREIGN_KEY(customerId) INT
        }

        TABLE(MovingCrew) {
            PRIMARY_KEY(crewId) INT AUTO_INCREMENT
            type VARCHAR(255)
            FOREIGN_KEY(shipmentId) INT
        }

        TABLE(Mover) {
            PRIMARY_KEY(moverId) INT AUTO_INCREMENT
            firstName VARCHAR(255)
            lastName VARCHAR(255)
            email VARCHAR(255)
            FOREIGN_KEY(movingCrewId) INT
        }

        TABLE(Driver) {
            PRIMARY_KEY(driverId) INT AUTO_INCREMENT
            firstName VARCHAR(255)
            lastName VARCHAR(255)
            email VARCHAR(255)
            FOREIGN_KEY(shipmentId) INT
        }

        TABLE(ShipmentReviewer) {
            PRIMARY_KEY(shipmentReviewerId) INT AUTO_INCREMENT
            firstName VARCHAR(255)
            lastName VARCHAR(255)
            email VARCHAR(255)
        }

        TABLE(Observer) {
            PRIMARY_KEY(observerId) INT AUTO_INCREMENT
            firstName VARCHAR(255)
            lastName VARCHAR(255)
            FOREIGN_KEY(shipmentId) INT
        }

        TABLE(Report) {
            PRIMARY_KEY(reportId) INT AUTO_INCREMENT
            name VARCHAR(50)
            type VARCHAR(50)
            date DATETIME
            validity DATETIME
        }
}

    Customer ||--|{ Shipment
    Truck ||--o{ Shipment
    Shipment ||--o{ MovingCrew
    MovingCrew ||--o{ Mover
    Shipment ||--o{ Observer
    Shipment ||--o{ ShipmentReviewer
    Driver ||--|| Truck
    Inventory ||--o{ Box
    Inventory ||--o{ Item
    Box ||--o{ Item
    Customer ||--o| Report
    Observer ||--o| Report
    Driver ||--|{ Report
    Shipment ||--|{ Inventory

@enduml
