@startuml
!include <archimate/Archimate>
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!include DEVICONS/java.puml
!include DEVICONS/mysql.puml
!include DEVICONS/react.puml
!include DEVICONS/html5.puml
!include DEVICONS/javascript.puml
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!include DEVICONS2/google.puml
!include DEVICONS2/npm_original_wordmark.puml
!define RECTANGLE_BORDER_COLOR white
!include DEVICONS2/tailwindcss.puml
!include DEVICONS2/typescript.puml

skinparam rectangle {
    BorderColor <<RECTANGLE_BORDER_COLOR>>
}

AddElementTag("webApp", $shape=RoundedBoxShape(), $bgColor="#f06529", $fontColor="white", $legendText="Web Application")
AddElementTag("webSite", $shape=RoundedBoxShape(), $bgColor="#61DAFB", $fontColor="#333333", $legendText="Single-Page Application")
AddElementTag("library", $shape=RoundedBoxShape(), $bgColor="#82A5AA", $fontColor="white", $legendText="Libraries")
AddElementTag("service", $shape=square(), $bgColor="#557C99", $fontColor="white", $legendText="Service\square")
AddRelTag("a_rel", $lineColor="Gray",$legendText="Application Relationships")

System_Boundary(ReactApplication, "ReactApplication") {
    Container(index, "Index Page", "HTML", "The entry point to the React Application.", $sprite="html5", $tags="webApp")

    rectangle "Components" as Components {
        Container(landingpage, "Landing Page", "TSX", "Displays the landing page of the application.", $sprite="typescript", $tags="webSite")
        Container(signuppage, "Signup Page", "TSX", "Handles user registration.", $sprite="typescript", $tags="webSite")
        Container(loginpage, "Login Page", "TSX", "Handles user login.", $sprite="typescript", $tags="webSite")
        Container(userhomepage, "User Home Page", "TSX", "Displays user dashboard.", $sprite="typescript", $tags="webSite")
        Container(shipmentquote, "Shipment Quote", "TSX", "Provides shipment quotations.", $sprite="typescript", $tags="webSite")
        Container(profilepage, "Profile Page", "TSX", "Manages user profile.", $sprite="typescript", $tags="webSite")
        Container(contactuspage, "Contact Us Page", "TSX", "Provides contact information.", $sprite="typescript", $tags="webSite")
        Container(shipmentspage, "Shipments Page", "TSX", "Displays all shipments.", $sprite="typescript", $tags="webSite")
        Container(shipmentdetails, "Shipment Details", "TSX", "Provides detailed view of shipments.", $sprite="typescript", $tags="webSite")
        Container(shipmentreviewer, "Shipment Reviewer", "TSX", "Reviews shipment details.", $sprite="typescript", $tags="webSite")
        Container(shipmentestimator, "Shipment Estimator", "TSX", "Estimates shipment costs.", $sprite="typescript", $tags="webSite")
    }

    rectangle "Libraries" as Libraries {
        Container(reactRouter, "React Router", "", "Library for handling routing in React applications.", $sprite="npm_original_wordmark", $tags="library")
        Container(axios, "Axios", "", "Library for making HTTP requests.", $sprite="npm_original_wordmark", $tags="library")
        Container(tailwind, "Tailwind", "", "utility-first CSS framework that provides pre-defined, composable classes for rapidly styling web elements, allowing tha ability to build and customize user interfaces efficiently.", $sprite="tailwindcss", $tags="library")
    }


}
rectangle "Services" as Services {
    Container(movingExpress, "Moving Express", "", "Main endpoint for HTTP requests.", $tags="service", $sprite="java")
}

Rel(index, landingpage, "Starts with", $tags="a_rel")
Rel(landingpage, loginpage, "Navigates to", $tags="a_rel")
Rel(landingpage, contactuspage, "Navigates to", $tags="a_rel")
Rel(landingpage, shipmentquote, "Navigates to", $tags="a_rel")
Rel(landingpage, signuppage, "Navigates to", $tags="a_rel")
Rel(landingpage, shipmentreviewer, "Navigates to", $tags="a_rel")
Rel(landingpage, shipmentestimator, "Navigates to", $tags="a_rel")

Rel(loginpage, userhomepage, "After Login", $tags="a_rel")
Rel(signuppage, userhomepage, "After Signup", $tags="a_rel")
Rel(shipmentspage, shipmentdetails, "Navigates to", $tags="a_rel")
Rel(landingpage, reactRouter, "Uses for navigation", $tags="a_rel")

Rel(userhomepage, profilepage, "Navigates to profile", $tags="a_rel")
Rel(userhomepage, shipmentspage, "Views shipments", $tags="a_rel")
Rel(shipmentdetails, userhomepage, "Back to shipments", $tags="a_rel")
Rel(profilepage, userhomepage, "Back to home", $tags="a_rel")
Rel(userhomepage, contactuspage, "Seeks support", $tags="a_rel")
Rel(shipmentspage, profilepage, "Navigates to profile", $tags="a_rel")
Rel(reactRouter, landingpage, "Handles navigation for", $tags="render_rel")
Rel(loginpage, movingExpress, "Makes login request to", $tags="a_rel")
Rel(signuppage, movingExpress, "Makes signup request to", $tags="a_rel")
Rel(shipmentspage, movingExpress, "Fetches shipment data from", $tags="a_rel")
Rel(shipmentdetails, movingExpress, "Fetches specific shipment data from", $tags="a_rel")
Rel(profilepage, movingExpress, "Fetches and updates user profile from", $tags="a_rel")
Rel(shipmentestimator, movingExpress, "Requests shipment estimate from", $tags="a_rel")

Rel(loginpage, axios, "Uses for HTTP requests", $tags="library_rel")
Rel(signuppage, axios, "Uses for HTTP requests", $tags="library_rel")
Rel(shipmentspage, axios, "Uses for HTTP requests", $tags="library_rel")
Rel(shipmentdetails, axios, "Uses for HTTP requests", $tags="library_rel")
Rel(profilepage, axios, "Uses for HTTP requests", $tags="library_rel")
Rel(shipmentestimator, axios, "Uses for HTTP requests", $tags="library_rel")



SHOW_LEGEND()
@enduml
