@startuml

left to right direction
skinparam actorStyle awesome
skinparam usecase {
    BackgroundColor DarkSeaGreen
    BorderColor DarkSlateGray
    ArrowColor Black
    ActorBorderColor black
    ActorFontName Courier
    ActorBackgroundColor<< Human >> Gold
}

actor Client as "Client" #LightBlue
actor "Moving Estimator" as MovingEstimator #LightGreen
actor "Truck Driver" as VanDriver #Orange
actor "Moving Crew" as MovingCrew #Purple
actor Management as "Management" #Yellow
actor "Shipment Reviewer" as ShipmentReviewer #Blue
actor "Observer" as Observer #LightCyan

rectangle "Moving Express System" {
    rectangle UseCases {
      usecase "1.0 Request a Quote" as UC1 #LightSeaGreen
      usecase "2.0 Request Shipment" as UC2 #LightSeaGreen
      usecase "3.0 Estimate Item Value" as UC3 #LightSeaGreen
      usecase "4.0 Estimate Shipment" as UC4 #LightSeaGreen
      usecase "5.0 Overview shipment" as UC5 #LightSeaGreen
      usecase "8.0 Transport Shipment" as UC8 #LightSeaGreen
      usecase "6.0 Packs Shipment" as UC6 #LightSeaGreen
      usecase "7.0 Load Shipment" as UC7 #LightSeaGreen
      usecase "9.0 Unload Shipment" as UC9 #LightSeaGreen
      usecase "10.0 Unpack Shipment" as UC10 #LightSeaGreen
      usecase "11.0 Generate Shipment Reports" as UC11 #LightSeaGreen
      usecase "12.0 Cancel Shipment" as UC12 #LightSeaGreen
    }
}

Client --|> Observer

Client ---> UC12
Client ---> UC6
Client ---> UC3
Client ---> UC2
Client ---> UC10

Observer --> UC1
Observer --> UC5

MovingEstimator --> UC2
MovingEstimator --> UC4
MovingEstimator --> UC3

VanDriver --> UC8

MovingCrew -[#Orange]--> UC6
MovingCrew -[#Orange]--> UC5
MovingCrew -[#Orange]--> UC7
MovingCrew -[#Orange]--> UC9
MovingCrew -[#Orange]--> UC10

UC11 <-- Management
VanDriver --> UC11

UC2 <-- ShipmentReviewer
UC1 <-- ShipmentReviewer
UC12 <-- ShipmentReviewer
UC5 <-- ShipmentReviewer

@enduml
