
# Default Spring Profile

#  profiles:
#    active: mysql
# Common Configuration

#spring:
#  profiles:
#    active: mysql1
server:
  error:
    include-message: always
logging:
  level:
    root: INFO
    com.example: DEBUG # package name
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
# for H2 tests
spring:
  config:
    activate:
      on-profile: h2
  h2:
  console:
    enabled: true

  datasource:
    url: jdbc:h2:mem:movingSystemDb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        auto-quote-keyword: true
---
#for docker
spring:
  datasource:
    url: jdbc:mysql://mysql1/MovingSystem-DB
    username: user
    password: pwd

  config:
    activate:
      on-profile: docker
  sql:
    init:
      platform: mysql
      mode: always

okta:
  oauth2:
    issuer: https://movingexpress.us.auth0.com/
    client-id: a9qWMiI6F273lcGJYjBhzN1ZPCBfgS3q
    client-secret: mcOpX5xdNvjGwBBzYi2CzopjuoZSggc8mRpYFj8vXCDpi8HpIk6m6vtLNRwBJ_6W

server.port: 8080
spring.datasource.hikari.initializationFailTimeout: 60000

