# Default Spring Profile

#  profiles:
#    active: mysql
# Common Configuration

#spring:
#  profiles:
#    active: mysql1
server:
  error:
    include-message: always
logging:
  level:
    root: INFO
    com.example: DEBUG # package name
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
---
# for H2 tests
spring:
  config:
    activate:
      on-profile: h2
  h2:
  console:
    enabled: true

  datasource:
    url: jdbc:h2:mem:movingSystemDb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        auto-quote-keyword: true
---
#for docker
spring:
  datasource:
    url: jdbc:mysql://mysql1/movingsystem-db
    username: user
    password: pwd

  jpa:
    hibernate:
      ddl-auto: none

  config:
    activate:
      on-profile: docker

  sql:
    init:
      platform: mysql
      mode: always

# Exclude SecurityAutoConfiguration to disable Spring Security auto-configuration
spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server.port: 8080
spring.datasource.hikari.initializationFailTimeout: 60000


