@startuml

left to right direction
skinparam actorStyle awesome
skinparam usecase {
    BackgroundColor DarkSeaGreen
    BorderColor DarkSlateGray
    ArrowColor Black
    ActorBorderColor black
    ActorFontName Courier
    ActorBackgroundColor<< Human >> Gold
}

actor Client as "Client" #LightBlue
actor "Moving Estimator" as MovingEstimator #LightGreen
actor "Truck Driver" as VanDriver #Orange
actor "Moving Crew" as MovingCrew #Purple
actor Management as "Management" #Yellow
actor "Shipment Reviewer" as ShipmentReviewer #Blue
actor "Observer" as Observer #LightCyan

rectangle "Moving Express System" {
    rectangle UseCases {
      usecase "2.0 Request Shipment" as UC2 #LightSeaGreen
      usecase "Request quote" as UC2_1
      usecase "Manage Shipment" as UC2_2
      usecase "Cancel Shipment" as UC2_3
      usecase "Verify Cancellation Shipment Request" as UC2_4

      note "If user wants to manage the shipment information they have so far" as N2
      note "If user clicks cancel shipment button" as N1
    }
}

UC2 <. UC2_1 : <<include>>
UC2 <. N2 : <<extends>>
UC2 <.. N1 : <<extends>>
N1 .. (UC2_3)
N2 .. (UC2_2)
UC2_3 <. UC2_4 : <<include>>

Client --|> Observer
Client --> UC2_1
Client --> UC2_3
Observer --> UC2_2

Observer --> UC2

MovingEstimator --> UC2

UC2_3 <-- ShipmentReviewer
UC2_4 <-- ShipmentReviewer
UC2 <-- ShipmentReviewer

@enduml


@startuml

left to right direction
skinparam actorStyle awesome

skinparam note {
 FontSize 10
}
skinparam usecase {
   BackgroundColor DarkSeaGreen
   BorderColor DarkSlateGray
   ArrowColor Black
   ActorBorderColor black
   ActorBackgroundColor<< Human >> Gold
}

actor Client as "Client" #LightBlue
actor "Moving Estimator" as MovingEstimator #LightGreen
actor "Shipment Reviewer" as ShipmentReviewer #Blue

rectangle "Moving Express System" {
   rectangle "UseCase 2" {
     usecase "1.0 Request a Quote" as UC1 #LightSeaGreen
     usecase "3.0 Estimate Item Value" as UC3 #LightSeaGreen
     usecase "4.0 Estimate Shipment" as UC4 #LightSeaGreen
     usecase "2.0 Request Shipment" as UC2 #LightSeaGreen
     usecase "12.0 Cancel Shipment" as UC12 #LightSeaGreen
     usecase "2.1 Manage Shipment" as UC2_1 #LightSeaGreen

     note "Optional if the client changes their mind" as N1
     note "Optional for advanced shipment handling and adjustments" as N2
   }
}

Client --> UC2


UC4 <-- MovingEstimator
UC3 <--- MovingEstimator

UC1 <-- ShipmentReviewer
UC12 <-- ShipmentReviewer
UC2 <---- ShipmentReviewer



UC2 ..> UC1 : <<Includes>>
UC2 ..> UC3 : <<Includes>>
UC2 ..> UC4 : <<Includes>>

UC2 <.. N1 : <<Extends>>
N1 .. (UC12)

UC2 <.. N2 : <<Extends>>
N2 .. (UC2_1)

@enduml
